fix: types.d.ts
due to "error TS2742:
The inferred type of 'default' cannot be named without a reference
to 'eslint-config-airbnb-flat/node_modules/@types/eslint'.
This is likely not portable. A type annotation is necessary.""